In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [98]:
df = pd.read_csv("Datos_limpios_Amsterdam.csv")
df.head(20)


Unnamed: 0 last_scraped  \
0            0   2024-09-05   
1            1   2024-09-05   
2            2   2024-09-05   
3            3   2024-09-06   
4            4   2024-09-05   
5            5   2024-09-05   
6            6   2024-09-06   
7            7   2024-09-06   
8            8   2024-09-06   
9            9   2024-09-06   
10          10   2024-09-06   
11          11   2024-09-06   
12          12   2024-09-05   
13          13   2024-09-06   
14          14   2024-09-06   
15          15   2024-09-06   
16          16   2024-09-06   
17          17   2024-09-06   
18          18   2024-09-06   
19          19   2024-09-06   

                                                 name  \
0                 Warm, cozy sunlighted downtown appt   
1                       Cozy apartment in city center   
2                  Loft style home nearby city centre   
3      Geweldige duurzame eco woonark op unieke plek!   
4                                   Old bar apartment   
5                 Cozy apartment at a great location!   
6   Unique houseboat in quiet Amsterdam water village   
7          Luxurious Private Studio with own entrance   
8   Appartement 80m2 with garden close to the Jordaan   
9                              Vondelpark appartement   
10                         Triple Room With City View   
11    Licht & authentiek appartement dichtbij centrum   
12            Room nearby Leidseplein in a canalhouse   
13    Full appartment next to the center of Amsterdam   
14                           Light and cosy apartment   
15          Nice apartment super close to Erasmuspark   
16  Renovated apartment & Roof terrace in Center East   
17             Apartment with private rootfop terrace   
18         Bright stylish home in city centre - 160m2   
19  Mooi appartement vlakbij het centrum van Amste...   

                                          description  \
0   2 room appt. 1.8 km from central station with ...   
1   Located in Amsterdam's sweet spot. A stone's t...   
2   Located in Amsterdam's sweet spot. A stone's t...   
3   This unique eco houseboat is located in the mo...   
4   This just renovated apartment for 6 persons is...   
5   Cozy renovated apartment on the 3th floor, loc...   
6   This spacious, two-storey houseboat with large...   
7   This centrally located accommodation is within...   
8   We have a just renovated beautiful apartment i...   
9   This beautiful apartment is just around the co...   
10  This tastefully decorated room has an elegant ...   
11  This centrally located apartment is located in...   
12  Comfortable room in a canal house near the cen...   
13  You'll have a great time at this comfortable p...   
14  Lovely pleasant area of Westerpark. Quiet and ...   
15  My apartment is in a nice aera of Amsterdam in...   
16  This is a great place for your stay in Amsterd...   
17  Nice apartment with private rooftop located in...   
18  The apartment consists of three levels.  Your ...   
19  This apartment is located against the Jordaan,...   

                                neighborhood_overview           host_location  \
0                                      Nothing to say  Amsterdam, Netherlands   
1                                       see the guide             Chicago, IL   
2                                      Nothing to say  Amsterdam, Netherlands   
3                                      Nothing to say  Amsterdam, Netherlands   
4   Our apartment is situated in the centre of Ams...          Not filled yet   
5                                      Nothing to say  Amsterdam, Netherlands   
6   Located in a peaceful water village, 5 minutes...  Amsterdam, Netherlands   
7                                      Nothing to say  Amsterdam, Netherlands   
8   It’s a friendly neighbourhood close to the Jor...  Amsterdam, Netherlands   
9                                      Nothing to say  Amsterdam, Netherlands   
10                                     Nothing to say          No

In [99]:
df = df[df['review_scores_cleanliness'] != 'Nothing']
df = df[df['host_is_superhost'] != 'Without information']
df = df[df['host_acceptance_rate'] != 'Without information']

In [100]:
df['host_acceptance_rate'] = df['host_acceptance_rate'].str.rstrip('%').astype(float) / 100
df['host_response_rate'] = df['host_response_rate'].str.rstrip('%').astype(float) / 100


In [101]:
Vars_Indep= df[['host_acceptance_rate','host_response_rate','review_scores_rating']]
Var_Dep= df['host_is_superhost']

In [102]:
X= Vars_Indep
y= Var_Dep

In [103]:
df.shape

(7169, 51)

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=None)

In [105]:
escalar= StandardScaler()

In [106]:
X_train= escalar.fit_transform(X_train)
X_test= escalar.transform(X_test)

In [107]:
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()

In [108]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [109]:
y_pred= algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], shape=(2151,), dtype=object)

In [110]:
from sklearn.metrics import confusion_matrix
matriz= confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[1646    0]
 [ 505    0]]


In [111]:
from sklearn.metrics import precision_score
precision = precision_score(y_test,y_pred,average="binary", pos_label="t")
print("Precisión del modelo:")
print(precision)

Precisión del modelo:
0.0


c:\Users\lapep\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [112]:
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.7652254765225477


In [113]:
from sklearn.metrics import recall_score
sensibilidad= recall_score(y_test, y_pred, average="binary",pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


In [114]:
Vars_Indep2= df[['review_scores_communication','host_response_rate','review_scores_rating']]
Var_Dep2= df['host_has_profile_pic']

In [115]:
X2= Vars_Indep2
y2= Var_Dep2

In [116]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2,y2,test_size=0.3, random_state=None)

In [117]:
escalar2= StandardScaler()

In [118]:
X_train2= escalar2.fit_transform(X_train2)
X_test2= escalar2.transform(X_test2)

In [119]:
from sklearn.linear_model import LogisticRegression
algoritmo2= LogisticRegression()

In [120]:
algoritmo2.fit(X_train2, y_train2)

LogisticRegression()

In [121]:
y_pred2= algoritmo2.predict(X_test2)
y_pred2

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2151,), dtype=object)

In [122]:
from sklearn.metrics import confusion_matrix
matriz2= confusion_matrix(y_test2, y_pred2)
print('Matriz de Confusión:')
print(matriz2)

Matriz de Confusión:
[[   0   21]
 [   0 2130]]


In [123]:
from sklearn.metrics import precision_score
precision2 = precision_score(y_test2,y_pred2,average="binary", pos_label="t")
print("Precisión del modelo:")
print(precision2)

Precisión del modelo:
0.9902370990237099


In [124]:
from sklearn.metrics import accuracy_score
exactitud2= accuracy_score(y_test2, y_pred2)
print('Exactitud del modelo:')
print(exactitud2)

Exactitud del modelo:
0.9902370990237099


In [125]:
from sklearn.metrics import recall_score
sensibilidad2= recall_score(y_test2, y_pred2, average="binary",pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad2)

Sensibilidad del modelo:
0.0


In [126]:
Vars_Indep3= df[['number_of_reviews','host_response_rate','availability_365']]
Var_Dep3= df['host_identity_verified']

In [127]:
X3= Vars_Indep3
y3= Var_Dep3

In [128]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3,y3,test_size=0.3, random_state=None)

In [129]:
escalar3= StandardScaler()

In [130]:
X_train3= escalar3.fit_transform(X_train3)
X_test3= escalar3.transform(X_test3)

In [131]:
from sklearn.linear_model import LogisticRegression
algoritmo3= LogisticRegression()

In [132]:
algoritmo3.fit(X_train3, y_train3)

LogisticRegression()

In [133]:
y_pred3= algoritmo3.predict(X_test3)
y_pred3

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2151,), dtype=object)

In [134]:
from sklearn.metrics import confusion_matrix
matriz3= confusion_matrix(y_test3, y_pred3)
print('Matriz de Confusión:')
print(matriz3)

Matriz de Confusión:
[[   0   35]
 [   0 2116]]


In [135]:
from sklearn.metrics import precision_score
precision3 = precision_score(y_test3,y_pred3,average="binary", pos_label="t")
print("Precisión del modelo:")
print(precision3)

Precisión del modelo:
0.9837284983728498


In [136]:
from sklearn.metrics import accuracy_score
exactitud3= accuracy_score(y_test3, y_pred3)
print('Exactitud del modelo:')
print(exactitud3)

Exactitud del modelo:
0.9837284983728498


In [137]:
from sklearn.metrics import recall_score
sensibilidad3= recall_score(y_test3, y_pred3, average="binary",pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad3)

Sensibilidad del modelo:
0.0


In [151]:
Vars_Indep4= df[['minimum_nights','maximum_nights','availability_365']]
Var_Dep4= df['has_availability']

In [152]:
X4= Vars_Indep4
y4= Var_Dep4

In [153]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4,y4,test_size=0.3, random_state=None)

In [154]:
escalar4= StandardScaler()

In [155]:
X_train4= escalar4.fit_transform(X_train4)
X_test4= escalar4.transform(X_test4)

In [156]:
from sklearn.linear_model import LogisticRegression
algoritmo4= LogisticRegression()

In [157]:
algoritmo4.fit(X_train4, y_train4)

LogisticRegression()

In [158]:
y_pred4= algoritmo4.predict(X_test4)
y_pred4

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2151,), dtype=object)

In [159]:
from sklearn.metrics import confusion_matrix
matriz4= confusion_matrix(y_test4, y_pred4)
print('Matriz de Confusión:')
print(matriz4)

Matriz de Confusión:
[[   0    8]
 [   0 2143]]


In [160]:
from sklearn.metrics import precision_score
precision4 = precision_score(y_test4,y_pred4,average="binary", pos_label="t")
print("Precisión del modelo:")
print(precision4)

Precisión del modelo:
0.9962807996280799


In [161]:
from sklearn.metrics import accuracy_score
exactitud4= accuracy_score(y_test4, y_pred4)
print('Exactitud del modelo:')
print(exactitud4)

Exactitud del modelo:
0.9962807996280799


In [207]:
from sklearn.metrics import recall_score
sensibilidad4= recall_score(y_test4, y_pred4, average="binary",pos_label="Has no information")
print('Sensibilidad del modelo:')
print(sensibilidad4)

Sensibilidad del modelo:
0.0


In [208]:
Vars_Indep5= df[['host_response_rate','number_of_reviews','review_scores_rating']]
Var_Dep5= df['instant_bookable']

In [209]:
X5= Vars_Indep5
y5= Var_Dep5

In [165]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5,y5,test_size=0.3, random_state=None)

In [166]:
escalar5= StandardScaler()

In [167]:
X_train5= escalar5.fit_transform(X_train5)
X_test5= escalar5.transform(X_test5)

In [168]:
from sklearn.linear_model import LogisticRegression
algoritmo5= LogisticRegression()

In [169]:
algoritmo5.fit(X_train5, y_train5)

LogisticRegression()

In [170]:
y_pred5= algoritmo5.predict(X_test5)
y_pred5

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], shape=(2151,), dtype=object)

In [171]:
from sklearn.metrics import confusion_matrix
matriz5= confusion_matrix(y_test5, y_pred5)
print('Matriz de Confusión:')
print(matriz5)

Matriz de Confusión:
[[1776   32]
 [ 315   28]]


In [172]:
from sklearn.metrics import precision_score
precision5 = precision_score(y_test5,y_pred5,average="binary", pos_label="t")
print("Precisión del modelo:")
print(precision5)

Precisión del modelo:
0.4666666666666667


In [173]:
from sklearn.metrics import accuracy_score
exactitud5= accuracy_score(y_test5, y_pred5)
print('Exactitud del modelo:')
print(exactitud5)

Exactitud del modelo:
0.8386796838679684


In [210]:
from sklearn.metrics import recall_score
sensibilidad5= recall_score(y_test5, y_pred5, average="binary",pos_label="f")
print('Sensibilidad del modelo:')
print(sensibilidad5)

Sensibilidad del modelo:
0.9823008849557522


In [175]:
df2= df

In [176]:
df2 = df2[df2['price'] != 'Does not say']

In [177]:
df2['price'] = df2['price'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\lapep\AppData\Local\Temp\ipykernel_6728\2595270364.py:1: SyntaxWarning: invalid escape sequence '\$'
  df2['price'] = df2['price'].replace('[\$,]', '', regex=True).astype(float)
C:\Users\lapep\AppData\Local\Temp\ipykernel_6728\2595270364.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['price'] = df2['price'].replace('[\$,]', '', regex=True).astype(float)


In [178]:
average_price = df2['price'].mean()
df2['price'] = ['higher' if x >= average_price else 'lower' for x in df2['price']]

C:\Users\lapep\AppData\Local\Temp\ipykernel_6728\3577721886.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['price'] = ['higher' if x >= average_price else 'lower' for x in df2['price']]


In [179]:
Vars_Indep6= df2[['host_response_rate','number_of_reviews','review_scores_rating']]
Var_Dep6= df2['price']

In [180]:
X6= Vars_Indep6
y6= Var_Dep6

In [181]:
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6,y6,test_size=0.3, random_state=None)

In [182]:
escalar6= StandardScaler()

In [183]:
X_train6= escalar6.fit_transform(X_train6)
X_test6= escalar6.transform(X_test6)

In [184]:
from sklearn.linear_model import LogisticRegression
algoritmo6= LogisticRegression()

In [185]:
algoritmo6.fit(X_train6, y_train6)

LogisticRegression()

In [186]:
y_pred6= algoritmo6.predict(X_test6)
y_pred6

array(['lower', 'lower', 'lower', ..., 'lower', 'lower', 'lower'],
      shape=(1509,), dtype=object)

In [187]:
from sklearn.metrics import confusion_matrix
matriz6= confusion_matrix(y_test6, y_pred6)
print('Matriz de Confusión:')
print(matriz6)

Matriz de Confusión:
[[ 10 551]
 [ 24 924]]


In [211]:
from sklearn.metrics import precision_score
precision6 = precision_score(y_test6,y_pred6,average="binary", pos_label="higher")
print("Precisión del modelo:")
print(precision6)

Precisión del modelo:
0.29411764705882354


In [189]:
from sklearn.metrics import accuracy_score
exactitud6= accuracy_score(y_test6, y_pred6)
print('Exactitud del modelo:')
print(exactitud6)

Exactitud del modelo:
0.6189529489728297


In [190]:
from sklearn.metrics import recall_score
sensibilidad6= recall_score(y_test6, y_pred6, average="binary",pos_label="lower")
print('Sensibilidad del modelo:')
print(sensibilidad6)

Sensibilidad del modelo:
0.9746835443037974


In [191]:
df2['property_type'] = ['entire' if 'entire' in str(x).lower() else 'other' for x in df2['property_type']]

C:\Users\lapep\AppData\Local\Temp\ipykernel_6728\2860930097.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['property_type'] = ['entire' if 'entire' in str(x).lower() else 'other' for x in df2['property_type']]


In [192]:
df = df[df['price'] != 'Does not say']
df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
C:\Users\lapep\AppData\Local\Temp\ipykernel_6728\3176375103.py:2: SyntaxWarning: invalid escape sequence '\$'
  df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)


In [193]:
Vars_Indep7= df[['accommodates','bedrooms','price']]
Var_Dep7= df2['property_type']

In [194]:
X7= Vars_Indep7
y7= Var_Dep7

In [195]:
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7,y7,test_size=0.3, random_state=None)

In [196]:
escalar7= StandardScaler()

In [197]:
X_train7= escalar7.fit_transform(X_train7)
X_test7= escalar7.transform(X_test7)

In [198]:
from sklearn.linear_model import LogisticRegression
algoritmo7= LogisticRegression()

In [199]:
algoritmo7.fit(X_train7, y_train7)

LogisticRegression()

In [200]:
y_pred7= algoritmo7.predict(X_test7)
y_pred7

array(['other', 'entire', 'entire', ..., 'entire', 'entire', 'entire'],
      shape=(1509,), dtype=object)

In [201]:
from sklearn.metrics import confusion_matrix
matriz7= confusion_matrix(y_test7, y_pred7)
print('Matriz de Confusión:')
print(matriz7)

Matriz de Confusión:
[[980  41]
 [301 187]]


In [212]:
from sklearn.metrics import precision_score
precision7 = precision_score(y_test7,y_pred7,average="binary", pos_label="entire")
print("Precisión del modelo:")
print(precision7)

Precisión del modelo:
0.7650273224043715


In [203]:
from sklearn.metrics import accuracy_score
exactitud7= accuracy_score(y_test7, y_pred7)
print('Exactitud del modelo:')
print(exactitud7)

Exactitud del modelo:
0.7733598409542743


In [204]:
from sklearn.metrics import recall_score
sensibilidad7= recall_score(y_test7, y_pred7, average="binary",pos_label="other")
print('Sensibilidad del modelo:')
print(sensibilidad7)

Sensibilidad del modelo:
0.3831967213114754


In [205]:
average_price = df2['accommodates'].mean()
df2['accommodates'] = ['higher' if x >= average_price else 'lower' for x in df2['accommodates']]

In [213]:
Vars_Indep8= df[['bedrooms','bathrooms','beds']]
Var_Dep8= df2['accommodates']

In [214]:
X8= Vars_Indep8
y8= Var_Dep8

In [215]:
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8,y8,test_size=0.3, random_state=None)

In [216]:
escalar8= StandardScaler()

In [217]:
X_train8= escalar8.fit_transform(X_train8)
X_test8= escalar8.transform(X_test8)

In [218]:
from sklearn.linear_model import LogisticRegression
algoritmo8= LogisticRegression()

In [219]:
algoritmo8.fit(X_train8, y_train8)

LogisticRegression()

In [220]:
y_pred8= algoritmo8.predict(X_test8)
y_pred8

array(['higher', 'lower', 'higher', ..., 'lower', 'higher', 'lower'],
      shape=(1509,), dtype=object)

In [221]:
from sklearn.metrics import confusion_matrix
matriz8= confusion_matrix(y_test8, y_pred8)
print('Matriz de Confusión:')
print(matriz8)

Matriz de Confusión:
[[599  86]
 [ 90 734]]


In [222]:
from sklearn.metrics import precision_score
precision8 = precision_score(y_test8,y_pred8,average="binary", pos_label="higher")
print("Precisión del modelo:")
print(precision8)

Precisión del modelo:
0.8693759071117562


In [223]:
from sklearn.metrics import accuracy_score
exactitud8= accuracy_score(y_test8, y_pred8)
print('Exactitud del modelo:')
print(exactitud8)

Exactitud del modelo:
0.8833664678595096


In [224]:
from sklearn.metrics import recall_score
sensibilidad8= recall_score(y_test8, y_pred8, average="binary",pos_label="lower")
print('Sensibilidad del modelo:')
print(sensibilidad8)

Sensibilidad del modelo:
0.8907766990291263


In [225]:
df2['room_type'] = ['apt' if 'entire' in str(x).lower() else 'other' for x in df2['room_type']]

In [226]:
Vars_Indep9= df[['accommodates','bedrooms','price']]
Var_Dep9= df2['room_type']

In [227]:
X9= Vars_Indep9
y9= Var_Dep9

In [228]:
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9,y9,test_size=0.3, random_state=None)

In [230]:
escalar9= StandardScaler()

In [231]:
X_train9= escalar9.fit_transform(X_train9)
X_test9= escalar9.transform(X_test9)

In [232]:
from sklearn.linear_model import LogisticRegression
algoritmo9= LogisticRegression()

In [233]:
algoritmo9.fit(X_train9, y_train9)

LogisticRegression()

In [234]:
y_pred9= algoritmo9.predict(X_test9)
y_pred9

array(['apt', 'other', 'apt', ..., 'apt', 'apt', 'other'],
      shape=(1509,), dtype=object)

In [235]:
from sklearn.metrics import confusion_matrix
matriz9= confusion_matrix(y_test9, y_pred9)
print('Matriz de Confusión:')
print(matriz9)

Matriz de Confusión:
[[1017   75]
 [ 200  217]]


In [236]:
from sklearn.metrics import precision_score
precision9 = precision_score(y_test9,y_pred9,average="binary", pos_label="apt")
print("Precisión del modelo:")
print(precision9)

Precisión del modelo:
0.8356614626129828


In [237]:
from sklearn.metrics import accuracy_score
exactitud9= accuracy_score(y_test9, y_pred9)
print('Exactitud del modelo:')
print(exactitud9)

Exactitud del modelo:
0.8177601060304838


In [238]:
from sklearn.metrics import recall_score
sensibilidad9= recall_score(y_test9, y_pred9, average="binary",pos_label="other")
print('Sensibilidad del modelo:')
print(sensibilidad9)

Sensibilidad del modelo:
0.5203836930455635


In [239]:
df2['review_scores_rating'] = df2['review_scores_rating'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\lapep\AppData\Local\Temp\ipykernel_6728\1751238844.py:1: SyntaxWarning: invalid escape sequence '\$'
  df2['review_scores_rating'] = df2['review_scores_rating'].replace('[\$,]', '', regex=True).astype(float)


In [240]:
average_price = df2['review_scores_rating'].mean()
df2['review_scores_rating'] = ['higher' if x >= average_price else 'lower' for x in df2['review_scores_rating']]

In [241]:
Vars_Indep10= df[['number_of_reviews','review_scores_cleanliness','review_scores_communication']]
Var_Dep10= df2['review_scores_rating']

In [242]:
X10= Vars_Indep10
y10= Var_Dep10

In [243]:
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10,y10,test_size=0.3, random_state=None)

In [244]:
escalar10= StandardScaler()

In [245]:
X_train10= escalar10.fit_transform(X_train10)
X_test10= escalar10.transform(X_test10)

In [246]:
from sklearn.linear_model import LogisticRegression
algoritmo10= LogisticRegression()

In [247]:
algoritmo10.fit(X_train10, y_train10)

LogisticRegression()

In [248]:
y_pred10= algoritmo10.predict(X_test10)
y_pred10

array(['higher', 'higher', 'higher', ..., 'lower', 'higher', 'lower'],
      shape=(1509,), dtype=object)

In [249]:
from sklearn.metrics import confusion_matrix
matriz10= confusion_matrix(y_test10, y_pred10)
print('Matriz de Confusión:')
print(matriz10)

Matriz de Confusión:
[[920  69]
 [172 348]]


In [250]:
from sklearn.metrics import precision_score
precision10 = precision_score(y_test10,y_pred10,average="binary", pos_label="higher")
print("Precisión del modelo:")
print(precision10)

Precisión del modelo:
0.8424908424908425


In [251]:
from sklearn.metrics import accuracy_score
exactitud10= accuracy_score(y_test10, y_pred10)
print('Exactitud del modelo:')
print(exactitud10)

Exactitud del modelo:
0.8402915838303512


In [252]:
from sklearn.metrics import recall_score
sensibilidad10= recall_score(y_test10, y_pred10, average="binary",pos_label="lower")
print('Sensibilidad del modelo:')
print(sensibilidad10)

Sensibilidad del modelo:
0.6692307692307692
